### ISSUE TITLE
Debugging broke

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/platform-renesas-ra#9]
```ini
[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
```
-->
```python
> pio debug --interface=gdb -- -x .pioinit
KeyError: Traceback (most recent call last):
  File "C:\Users\Max\AppData\Roaming\Python\Python311\site-packages\platformio\__main__.py", line 103, in main
    cli()  # pylint: disable=no-value-for-parameter
    ^^^^^
  File "C:\Users\Max\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Max\AppData\Roaming\Python\Python311\site-packages\platformio\cli.py", line 85, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\AppData\Roaming\Python\Python311\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\AppData\Roaming\Python\Python311\site-packages\platformio\debug\cli.py", line 104, in cli
    debug_config = _configure(*configure_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\AppData\Roaming\Python\Python311\site-packages\platformio\debug\cli.py", line 113, in _configure
    debug_config = DebugConfigFactory.new(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\AppData\Roaming\Python\Python311\site-packages\platformio\debug\config\factory.py", line 48, in new
    return config_cls(platform, project_config, env_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\AppData\Roaming\Python\Python311\site-packages\platformio\debug\config\generic.py", line 38, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\Max\AppData\Roaming\Python\Python311\site-packages\platformio\debug\config\base.py", line 52, in __init__
    self.server = self._configure_server()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\AppData\Roaming\Python\Python311\site-packages\platformio\debug\config\base.py", line 182, in _configure_server
    self.platform.get_package_dir(server_package)
  File "C:\Users\Max\AppData\Roaming\Python\Python311\site-packages\platformio\platform\_packages.py", line 32, in get_package_dir
    pkg = self.get_package(name)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\AppData\Roaming\Python\Python311\site-packages\platformio\platform\_packages.py", line 29, in get_package
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Max\AppData\Roaming\Python\Python311\site-packages\platformio\platform\_packages.py", line 21, in get_package_spec
    owner=self.packages[name].get("owner"),
          ~~~~~~~~~~~~~^^^^^^
KeyError: 'tool-openocd'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `python -m pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================
```

And that's after a clean reinstall of renesas-ra@1.0.0. The `platform.py` logic might no be able to handle the case with the Arduino Uno R4 WiFi which needs tool-bossac to preload but at the same time tool-openocd to open the debug session.

**Comment by maxgerhardt** [comment]
Adding
```python
            print("For package " + str(package) + " target " + str(targets) + " use conditions: " + str(use_conditions))
```
before

https://github.com/platformio/platform-renesas-ra/blob/a0e681776997c6896ddf9fa6950d4468090bcd12/platform.py#L39-L42

shows

```
> pio debug --interface=gdb -- -x .pioinit
For package tool-jlink target [] use conditions: [False, False, False, False]
For package tool-openocd target [] use conditions: [False, False, False, False]
For package tool-dfuutil-arduino target [] use conditions: [False, False, False, False]
For package tool-bossac target [] use conditions: [False, False, False, True]
```
And so the tool-openocd package is thrown out.
